name: admin_app
description: "SecureChat admin panel - responsive web app."
publish_to: none
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^18.0.1
  shared:
    path: ../../packages/shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
